allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects { project ->
    def setNamespace = {
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    if (project.group != null && !project.group.toString().isEmpty()) {
                        namespace = project.group.toString()
                    } else {
                        namespace = "com.plugin.${project.name.replace('-', '_')}"
                    }
                }
            }
        }
    }
    if (project.state.executed) {
        setNamespace()
    } else {
        project.afterEvaluate {
            setNamespace()
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
